v2:
  requires:
    type: object
    properties:
      service:
        type: string
      port:
        type: integer
      namespace:
        type: string
      prefix:
        type: string
      rewrite:
        type: string
    required:
      - service
      - port
      - namespace
      - prefix
v1:
  requires:
    type: object
    properties:
      service:
        type: string
      port:
        type: integer
      prefix:
        type: string
      rewrite:
        type: string
    required:
      - service
      - port
      - prefix
